# Dockerfile
FROM kalilinux/kali-rolling

RUN apt update && apt install -y \
    python3 \
    python3-pip \
    nmap \
    curl \
    wget \
    dnsutils \
    traceroute \
    nikto \
    crunch \
    iptables \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .

CMD ["python3", "phish_spyd3r_bot.py"]